info:
  app:
    name: catalog-recommend-service
    description: Service to give recommendations to users

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8022

spring:  

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: docker

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/